betterCreativeInventory.loader={}
betterCreativeInventory.loader.map={
	lumps_ingots = {
		'default:iron_lump',
		'default:steel_ingot',
		'default:gold_lump',
		'default:gold_ingot',
		'default:copper_lump',
		'default:copper_ingot',
		'default:coal_ingot',
		'default:bronze_ingot',
		'default:mese_crystal',
		'default:mese_crystal_fragment',
		'default:diamond',
		'default:coal_lump',
		
		'default:diamondblock',
		'default:bronzeblock',
		'default:copperblock',
		'default:goldblock',
		'default:mese',
		'default:coalblock',
		'default:steelblock',
	},
	
	buckets = {
		'oil:fuel_bucket',
		'oil:bucket_oil',
		'bucket:bucket_empty',
		'bucket:bucket_water',
		'bucket:bucket_lava',
	},
	
	earth = {
		'default:dirt',
		'default:obsidian',
		'default:obsidian_shard',
		'default:dirt_with_grass',
		'default:dirt_with_snow',
		'default:stone',
		'default:cobble',
		'default:gravel',
		'default:ice',
		'default:snow',
		'default:mossycobble',
		'default:sand',
		'default:desert_sand',
		'default:desert_stone',
		'default:clay',
		'default:snowblock',
		'default:sandstone',
		'default:sandstonebrick',
	
		'default:stone_with_coal',
		'default:stone_with_copper',
		'default:stone_with_diamond',
		'default:stone_with_gold',
		'default:stone_with_iron',
		'default:stone_with_mese',
	},
	
	Beds = {
		'beds:bed_bottom_red',
		'beds:bed_bottom_orange',
		'beds:bed_bottom_yellow',
		'beds:bed_bottom_green',
		'beds:bed_bottom_blue',
		'beds:bed_bottom_violet',
		'beds:bed_bottom_black',
		'beds:bed_bottom_grey',
		'beds:bed_bottom_white',
	},
	
	Misc = {
		'bones:bones',
		'bones:single_bone',
		'default:torch',
		'default:nyancat',
		'default:nyancat_rainbow',
		'farming:scarecrow',
		'farming:scarecrow_light',
		'farming:string',
		'fire:basic_flame',
		'lightingplus:glowstone',
		'screwdriver:screwdriver',
	},
	
	
	Transportation = {
		'carts:cart',
		'carts:brakerail',
		'carts:powerrail',
		'default:rail',
		'boats:boat',
	},
	
	
	Foods = {
		'default:apple',
		'farming:bread',
		'farming:flour',
		'farming:pumpkin_flour',
		'farming:pumpkin_bread',
		'farming_plus:banana',
		'farming_plus:carrot_item',
		'farming_plus:strawberry_item',
		'farming_plus:rhubarb_item',
		'farming_plus:tomato_item',
		'farming_plus:orange_item',
		'morefoods:chocolate',
		'morefoods:choc_powder',
	},
	
	
	Tools = {
		'default:axe_bronze',
		'default:axe_diamond',
		'default:axe_mese',
		'default:axe_steel',
		'default:axe_stone',
		'default:axe_wood',
		
		'default:pick_bronze',
		'default:pick_diamond',
		'default:pick_mese',
		'default:pick_steel',
		'default:pick_stone',
		'default:pick_wood',
		
		'default:shovel_bronze',
		'default:shovel_diamond',
		'default:shovel_mese',
		'default:shovel_steel',
		'default:shovel_stone',
		'default:shovel_wood',
		
		'default:sword_bronze',
		'default:sword_diamond',
		'default:sword_mese',
		'default:sword_steel',
		'default:sword_stone',
		'default:sword_wood',
		
		'farming:hoe_bronze',
		'farming:hoe_steel',
		'farming:hoe_stone',
		'farming:hoe_wood',
	},
	
	
	Building_Matter = {
		'default:brick',
		'default:wood',
		'default:junglewood',
		'default:clay_lump',
		'default:clay_brick',
		'default:glass',
		'default:stonebrick',
		'default:desert_stonebrick',
		'default:fence_wood',
		'default:ladder',
		'default:obsidian_glass',
	},
	
	
	Organic_matter = {
		'default:tree',
		'default:jungletree',
		'default:leaves',
		'default:jungleleaves',
		'default:cactus',
		'default:sapling',
		'default:junglesapling',
		'default:dry_shrub',
		'default:grass_1',
		'default:junglegrass',
		'default:paper',
		'default:papyrus',
		'default:stick',
		'default:scorched_stuff',
		
		'farming:big_pumpkin',
		'farming:pumpkin',
		'farming:pumpkin_face',
		'farming:pumpkin_face_light',
		'farming:pumpkin_seed',
		'farming:seed_cotton',
		'farming:seed_wheat',
		'farming:weed',
		'farming:wheat',
		
		'farming_plus:banana_sapling',
		'farming_plus:cocoa_sapling',
		
		'farming_plus:carrot_seed',
		'farming_plus:potatoe_seed',
		'farming_plus:orange_seed',
		'farming_plus:rhubarb_seed',
		'farming_plus:tomato_seed',
		'farming_plus:strawberry_seed',
		
		'farming_plus:cocoa',
		'farming_plus:cocoa_bean',
		'farming_plus:potatoe_item',
		
		'flowers:dandelion_white',
		'flowers:dandelion_yellow',
		'flowers:geranium',
		'flowers:rose',
		'flowers:tulip',
		'flowers:viola',
		
		'flowers:flower_pot',
		'flowers:potted_dandelion_white',
		'flowers:potted_dandelion_yellow',
		'flowers:potted_geranium',
		'flowers:potted_rose',
		'flowers:potted_tulip',
		'flowers:potted_viola',
		
		'flowers:seaweed',
		'flowers:waterlily',
		
		'junglegrass:medium',
		'junglegrass:short',
		'junglegrass:shortest',
		
		'misc:fertilizer',
	},
	
	
	Decor = {
		'default:book',
		'default:bookshelf',
		'default:chest',
		'default:chest_locked',
		'default:furnace',
		'default:sign_wall',
		'doors:door_wood',
		'doors:door_steel',
		
		'dye:black',
		'dye:blue',
		'dye:brown',
		'dye:cyan',
		'dye:dark_green',
		'dye:dark_grey',
		'dye:green',
		'dye:grey',
		'dye:magenta',
		'dye:orange',
		'dye:pink',
		'dye:red',
		'dye:violet',
		'dye:white',
		'dye:yellow',
	},
	
	mesecons = {
		'digilines:wire_std_00000000',
		'digilines_lcd:lcd',
		'digilines_lightsensor:lightsensor',
		'digilines_rtc:rtc',
	},
	
	Industrial = {
		'homedecor:plastic_base',
		'homedecor:plastic_sheeting',
		'laser:laser_blue',
		'laser:laser_green',
		'laser:laser_red',
	},
}

betterCreativeInventory.category.move = {
	{"buildtest", "Industrial"},
	{"itest", "Industrial"},
	{"morechests", "Decor"},
	{"poison", "Misc"},
	{"oil", "Misc"},
	{"laser", "Misc"},
	{"scuba", "Misc"},
	{"wool", "mobs"},
	{"wireless", "mesecons"},
	{"moredigi", "mesecons"},
	{"vines", "Organic_matter"},
	{"tnt", "Misc"},
	{"vessels", "Misc"},
	{"stairs", "Building_Matter"},
	{"jukebox", "Misc"},
	{"keys", "Misc"},
	{"pipeworks", "Industrial"},
	{"3dforniture", "Decor"},
	{"infrastructure", "Industrial"},
	{"moreblocks", "Decor"},
	{"digipad", "mesecons"},
	{"jail", "Misc"},
	{"moretrees", "Organic_matter"},
	{"misc", "Misc"},
	{"chems", "Misc"},
	{"potions", "Misc"},
}